os: linux
dist: bionic
language: go

go:
  - 1.15.x

env:
  - DOCKER_TAG=$TRAVIS_TAG

before_install:
  - wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
  - echo deb https://download.ceph.com/debian-nautilus/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
  - sudo DEBIAN_FRONTEND=noninteractive apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y librados-dev librbd-dev

install:
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -tags nautilus -v -race -count=1 -coverprofile=collectors.coverprofile ./...
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci

after_success:
  - export DOCKER_REPO="digitalocean/ceph_exporter"
  - if [ ! -z "$TRAVIS_TAG" ]; then
    docker build -t $DOCKER_REPO:$DOCKER_TAG .;
    docker tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REPO:latest;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi
