language: go
sudo: required
dist: trusty

go:
  - 1.5

before_install:
  - sudo apt-get update
  - sudo apt-get install -y librados-dev librbd-dev

install:
  - go get github.com/ceph/go-ceph
  - go get github.com/prometheus/client_golang/prometheus
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci ./...
