# Example usage of exporter in use

# In this case, it depends on the proper ceph keys in the correct place.

version: '2'

services:
  prometheus:
    image: prom/prometheus:v1.6.1
    volumes:
        - './prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'
  ceph-exporter:
    image: digitalocean/ceph_exporter
    volumes:
        - '/etc/ceph:/etc/ceph'
    ports:
        - '9128:9128'
  grafana:
    image: grafana/grafana:4.2.0
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=test
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
